
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mall
    password: passMall123
    url: jdbc:mysql://rm-uf6t9m0yx22dxrya5no.mysql.rds.aliyuncs.com:3306/mall?characterEncoding=UTF8&useSSL=false
  redis:
    host: 47.103.57.195
    port: 6379
  rabbitmq:
    addresses:  127.0.0.1
    port: 5672
    username: guest
    password: guest


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 200